name: Generate Snake Game Contribution

on:
  schedule: 
    - cron: "0 0 * * *" 
  workflow_dispatch:

  jobs: 
    generate: 
       runs-on: ubutun-latest
      steps: 
       - name: Checkout do repositorio
         uses: actions/checkout@v3

       - name: Gerar snake.svg
         uses: Platane/snk@v3
         with:
           github_user_name: AlyssonDev1914
           outputs: dist

      - name: Enviar snake.svg para a brach output
        uses: crazy-max/ghaction-github-pages@v3

        with:
          target_brach: output
          build_dir: dist
          env:

          GITHUB_TOKEN: $ {{ secrets_GITHUB_TOKEN }}
